bootc pipes for users

diff --git a/deployment/openshift/bootstrap-lab/manifests/pipelines/05-user-pipelines.yaml b/deployment/openshift/bootstrap-lab/manifests/pipelines/05-user-pipelines.yaml
--- a/deployment/openshift/bootstrap-lab/manifests/pipelines/05-user-pipelines.yaml
+++ b/deployment/openshift/bootstrap-lab/manifests/pipelines/05-user-pipelines.yaml
@@ -223,7 +223,7 @@ spec:
                   for arch in \$(echo \$(params.PLATFORMS) | tr ',' ' '); do
                     tag="\${arch//\//-}"
                     echo "Building for \$arch -> \$tag"
-                    podman build --arch \${arch##*/} -f \$(params.CONTAINERFILE) -t \$IMAGE-\$tag \$(params.CONTEXT)
+                    podman build --platform \${arch##*/} -f \$(params.CONTAINERFILE) -t \$IMAGE-\$tag \$(params.CONTEXT)
                     podman push \$IMAGE-\$tag
                   done
 
@@ -353,4 +353,254 @@ spec:
       restartPolicy: OnFailure
   backoffLimit: 1
 
+
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: bootc-user-pipelines-create
+  namespace: openshift-gitops
+  annotations:
+    argocd.argoproj.io/sync-wave: "5"
+spec:
+  template:
+    spec:
+      serviceAccountName: openshift-gitops-argocd-application-controller
+      containers:
+      - name: shell
+        image: quay.io/luisarizmendi/ocp-job:latest  
+        command: ["/bin/sh", "-c"]
+        args:
+        - |
+
+          apply_with_retries() {
+            local attempt=0
+            local max_attempts=5
+            local delay=5
+
+            while true; do
+              if "$@"; then
+                echo "Apply succeeded: $*"
+                return 0
+              fi
+
+              attempt=$(( attempt + 1 ))
+              if [ "$attempt" -ge "$max_attempts" ]; then
+                echo "Apply failed after $max_attempts attempts: $*"
+                return 1
+              fi
+
+              echo "Apply failed, retrying in $delay seconds... (attempt $attempt)"
+              sleep "$delay"
+            done
+          }
+
+
+          while true; do
+              if oc get tasks.tekton.dev -n default &> /dev/null; then
+                  echo "Tekton API (tekton.dev/v1) is ready"
+                  break
+              fi
+            sleep 10
+          done
+
+          # Loop through users user01 to user50 and user99
+          for i in $(seq -w 1 50) 99; do
+            username="user$i"
+            pipeline_namespace="${username}-tools"
+
+            while true; do
+                if oc get namespace "$pipeline_namespace" &> /dev/null; then
+                    echo "Namespace $pipeline_namespace has been created"
+                    break
+                fi
+                sleep 10
+            done    
+
+
+
+
+          apply_with_retries  oc apply -f - <<EOFUP
+          ---
+          apiVersion: tekton.dev/v1
+          kind: Pipeline
+          metadata:
+            name: bootc-image-build
+            namespace: $pipeline_namespace
+          spec:
+            params:
+              - name: bootc-build-files-repo-url
+                description: "Repo url with bootc image build files"
+                type: string
+              - name: bootc-build-files-repo-branch
+                description: "Repo branch where bootc image build files are located"
+                type: string
+                default: "main"
+              - name: bootc-build-files-repo-subpath
+                description: "Repo subpath where bootc image build files are located"
+                default: "."
+                type: string
+              - name: container-registry-image-name
+                type: string
+                description: "Full image name including registry and tag, for example registry.io/user/image:tag"
+
+            workspaces:
+              - name: shared-workspace
+                description: "Workspace used for sharing data between tasks"
+              - name: pull-secret
+                description: "Secret with the Red Hat container registry pull credentials"
+              - name: push-secret
+                description: "Secret with the credentials to push the image"
+              - name: redhat-credentials
+                description: "Secret with the Red Hat cuer and password"
+
+            tasks:
+              - name: get-build-files
+                taskRef:
+                  name: git-clone-and-copy-subpath
+                  kind: Task
+                params:
+                  - name: bootc-build-files-repo-url
+                    value: \$(params.bootc-build-files-repo-url)
+                  - name: bootc-build-files-repo-branch
+                    value: \$(params.bootc-build-files-repo-branch)
+                  - name: bootc-build-files-repo-subpath
+                    value: \$(params.bootc-build-files-repo-subpath)
+                workspaces:
+                  - name: output
+                    workspace: shared-workspace 
+
+              - name: build-and-push-image
+                runAfter:
+                  - get-build-files
+                taskRef:
+                  name: bootc-build-and-push
+                  kind: Task
+                params:
+                  - name: IMAGE
+                    value: \$(params.container-registry-image-name)
+                workspaces:
+                  - name: source
+                    workspace: shared-workspace
+                  - name: redhat-credentials
+                    workspace: redhat-credentials
+                  - name: pull-secret
+                    workspace: pull-secret
+                  - name: push-secret
+                    workspace: push-secret
+
+          ---
+          apiVersion: tekton.dev/v1
+          kind: Task
+          metadata:
+            name: bootc-build-and-push
+            namespace: $pipeline_namespace
+          spec:
+            params:
+              - name: IMAGE
+                description: Full image name including registry
+              - name: CONTAINERFILE
+                description: Path to Containerfile
+                default: ./Containerfile
+              - name: CONTEXT
+                description: Build context
+                default: ./
+              - name: PLATFORMS
+                description: Comma-separated target platforms (e.g., linux/amd64,linux/arm64)
+                default: linux/amd64,linux/arm64
+            workspaces:
+              - name: source
+              - name: pull-secret
+                optional: true
+                mountPath: /root/pull-secret
+              - name: pull-secret
+                optional: true
+                mountPath: /root/push-secret
+              - name: redhat-credentials
+                optional: true
+                mountPath: /root/redhat-credentials
+            steps:
+              - name: build-and-push
+                image: quay.io/centos-bootc/bootc-image-builder:latest
+                securityContext:
+                  privileged: true  # Required for QEMU & binfmt_misc
+                  runAsUser: 0
+                  seLinuxOptions:
+                    type: container_file_t
+                workingDir: \$(workspaces.source.path)
+                script: |
+                  #!/bin/bash
+                  set -e
+                  export IMAGE=\$(params.IMAGE)
+                  IMAGE="\${IMAGE#http://}"
+                  IMAGE="\${IMAGE#https://}"
+                  IMAGE="\${IMAGE//\/\//\/}"
+
+                  echo "Enabling binfmt_misc for cross-arch builds..."
+                  podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
+
+                  echo "Creating multiarch manifest: \$IMAGE"
+                  for arch in \$(echo \$(params.PLATFORMS) | tr ',' ' '); do
+                    tag="\${arch//\//-}"
+                    echo "Building for \$arch -> \$tag"
+                    podman build --authfile /root/pull-secret/pull-secret.txt \
+                      --volume /root/etc-pki-entitlement/entitlement.pem:/etc/pki/entitlement/entitlement.pem:ro --volume /root/etc-pki-entitlement/entitlement-key.pem:/etc/pki/entitlement/entitlement-key.pem:ro \
+                      --platform \${arch##*/} -f \$(params.CONTAINERFILE) -t \$IMAGE-\$tag \$(params.CONTEXT)
+                    podman push --authfile=/root/push-secret/push-secret.txt \$IMAGE-\$tag         
+                  done
+                  echo "Creating and pushing manifest list..."
+                  podman manifest create \$IMAGE
+                  for arch in \$(echo \$(params.PLATFORMS)  | tr ',' ' '); do
+                    tag="\${arch//\//-}"
+                    podman manifest add \$IMAGE \$IMAGE-\$tag
+                  done
+                  podman manifest push --authfile=/root/push-secret/push-secret.txt --all \$IMAGE docker://\$IMAGE
+              
+          ---
+          apiVersion: tekton.dev/v1
+          kind: Task
+          metadata:
+            name: git-clone-and-copy-subpath
+            namespace: $pipeline_namespace
+          spec:
+            params:
+              - name: bootc-build-files-repo-url
+                description: The git repository URL to clone
+              - name: bootc-build-files-repo-branch
+                description: The branch to checkout
+                default: main
+              - name: bootc-build-files-repo-subpath
+                description: Subdirectory path to copy from the cloned repo
+                default: "."
+            workspaces:
+              - name: output
+                description: Target workspace where the files will be copied
+            steps:
+              - name: clone-and-copy
+                image: alpine/git:latest
+                script: |
+                  #!/bin/sh
+                  set -e
+
+                  echo "Cloning repo: \$(params.bootc-build-files-repo-url)"
+                  rm -rf /tmp/repo && git clone --depth 1 --branch \$(params.bootc-build-files-repo-branch) \$(params.bootc-build-files-repo-url) /tmp/repo
+
+                  echo "Copying subpath: \$(params.bootc-build-files-repo-subpath)"
+                  cp -r /tmp/repo/\$(params.bootc-build-files-repo-subpath)/* \$(workspaces.output.path)/
+          EOFUP
+
+
+
+          done
+          echo "Environment ready!"
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - "ALL"
+          runAsNonRoot: true
+          seccompProfile:
+            type: RuntimeDefault
+      restartPolicy: OnFailure
+  backoffLimit: 1
 
